vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        picture:
            uri_prefix: /images/picture
            upload_destination: '%kernel.project_dir%/public/images/picture'
            namer: Vich\UploaderBundle\Naming\OrignameNamer